version: '3'

services:

  node:
    image: node:20.4
    tty: true
    container_name: ${PROJECT_NAME}_node
    working_dir: /var/www/${PROJECT_NAME}/site
    volumes:
      - .:/var/www/${PROJECT_NAME}/site
    ports:
      - ${PORT}:${PORT}
    networks:
      - common

networks:
  common:
    external: true
